apiVersion: apps/v1
kind: Deployment
metadata:
  name: srespace-frontend
  namespace: {{ .Values.namespace }}
  labels: { app: srespace-frontend }
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: { app: srespace-frontend }
  template:
    metadata:
      labels: { app: srespace-frontend }
      annotations: { linkerd.io/inject: enabled }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: "{{ .Values.frontend.image.pullPolicy }}"
          ports: [ { containerPort: {{ .Values.frontend.service.port }}, name: http } ]
          envFrom: [ { secretRef: { name: {{ .Values.envFromSecret | quote }} } } ]
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: srespace-frontend
  namespace: {{ .Values.namespace }}
  labels: { app: srespace-frontend }
spec:
  selector: { app: srespace-frontend }
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
      name: http
