image:
  repository: LOCATION-docker.pkg.dev/PROJECT/REPO/projectflow
  tag: "dev-latest"
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  className: traefik
  hosts: [ projectflow.example.com ]
envFromSecret: projectflow-env
resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits:   { cpu: 300m, memory: 512Mi }
hpa:
  enabled: false

