{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata: { name: projectflow }
spec:
  entryPoints: [ websecure ]
  routes:
    - match: Host(`{{ index .Values.ingress.hosts 0 }}`)
      kind: Rule
      services: [ { name: projectflow, port: 80 } ]
  tls: {}
{{- end }}

