apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: { name: projectflow-env, namespace: apps }
spec:
  refreshInterval: 15m
  secretStoreRef: { name: vault, kind: ClusterSecretStore }
  target: { name: projectflow-env, creationPolicy: Owner }
  data:
    - secretKey: DATABASE_URL
      remoteRef: { key: secret/Dev-secret/projectflow, property: DATABASE_URL }
    - secretKey: JWT_SECRET
      remoteRef: { key: secret/Dev-secret/projectflow, property: JWT_SECRET }
    - secretKey: REDIS_URL
      remoteRef: { key: secret/Dev-secret/projectflow, property: REDIS_URL }

