apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: {name: platform-tools, namespace: argocd}
spec:
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: platform-tools
    - server: https://kubernetes.default.svc
      namespace: apps
    - server: https://kubernetes.default.svc
      namespace: linkerd
  sourceRepos: ['*']
  clusterResourceWhitelist: [{group: '*', kind: '*'}]
