apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: external-secrets-dev, namespace: argocd }
spec:
  project: platform-tools
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.5
      helm: { valueFiles: [ $values/gitops/platform-tools/values/dev/external-secrets.yaml ] }
    - repoURL: https://github.com/nolet7/total-gitops.git
      targetRevision: master
      ref: values
  destination: { server: https://kubernetes.default.svc, namespace: platform-tools }
  syncPolicy: { automated: { selfHeal: true, prune: true } }

