resources:
  # --- DEV controllers we need ---
  - external-secrets-app-dev.yaml   # ESO + CRDs
  - traefik-app-dev.yaml            # Ingress
  - kyverno-app-dev.yaml            # (optional) policies
  - mysql-app-dev.yaml              # In-cluster MySQL

  # --- Policies (safe to keep) ---
  - kyverno-policies/require-requests-limits.yaml
  - kyverno-policies/disallow-latest-tag.yaml
  - kyverno-policies/verify-cosign-images.yaml

  # --- ExternalSecret objects that feed MySQL + your app ---
  - stores/externalsecrets/mysql-auth.yaml
  - stores/externalsecrets/srespace-env.yaml
