apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: kyverno-dev, namespace: argocd }
spec:
  project: platform-tools
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.6
  destination: { server: https://kubernetes.default.svc, namespace: platform-tools }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true", "SkipDryRunOnMissingResource=true" ]
