apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: { name: vault }
spec:
  provider:
    vault:
      server: "http://48.217.51.59:8200"
      version: v2
      auth:
        kubernetes:
          mountPath: auth/kubernetes
          role: es-reader

